#!/bin/bash

scriptstart=$(date +'%s')
LOGFILE="/boot/logs/Reboot_Download_Pack.txt"

# Define the names of the qBittorrent, Jackett, Radarr, and Sonarr containers
DELUGE_CONTAINER_NAME="delugevpn"
FLARE_CONTAINER_NAME="flaresolverr"
PROWLARR_CONTAINER_NAME="Prowlarr"
RADARR_CONTAINER_NAME="radarr"
SONARR_CONTAINER_NAME="sonarr"
READARR_CONTAINER_NAME="Readarr"
LIDARR_CONTAINER_NAME="lidarr"
UNPACKERR_CONTAINER_NAME="unpackerr"
OVERSEERR_CONTAINER_NAME="overseerr"

# Restart Deluge container
docker restart $DELUGE_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Deluge" >> $LOGFILE 2>&1
sleep 45

# Restart FlareSolver container
docker restart $FLARE_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted FlareSolverr" >> $LOGFILE 2>&1

# Restart Jackett container
docker restart $PROWLARR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Prowlarr" >> $LOGFILE 2>&1

# Restart Radarr container
docker restart $RADARR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Radarr" >> $LOGFILE 2>&1

# Restart Sonarr container
docker restart $SONARR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Sonarr" >> $LOGFILE 2>&1

# Restart Readarr container
docker restart $READARR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Readarr" >> $LOGFILE 2>&1

# Restart Lidarr container
docker restart $LIDARR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Lidarr" >> $LOGFILE 2>&1

# Restart Unpacker container
docker restart $UNPACKERR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Unpacker" >> $LOGFILE 2>&1

# Restart Overseerr container
docker restart $OVERSEERR_CONTAINER_NAME && echo "$(date "+%m-%d-%Y %T") : Restarted Overseerr" >> $LOGFILE 2>&1

# Delete dangling docker images
docker image prune -f
echo "$(date "+%m-%d-%Y %T") : Cleaned up dangling docker images" >> $LOGFILE 2>&1
